CREATE TABLE TRAMITE (
    ID_TRAMITE INT PRIMARY KEY,
    NOMBRE_TRAMITE VARCHAR(255) NOT NULL,
    DESC_TRAMITE VARCHAR(255)

);

CREATE TABLE DOCUMENTACION (
  ID_TRAMITE INT,
  ID_TIPO_DOC INT UNIQUE,
  FLG_ANEXO BOOLEAN,
  PRIMARY KEY (ID_TRAMITE, ID_TIPO_DOC)
);

CREATE TABLE ESTRUCTURA (
    ID_TIPO_DOC INT,
    ID_ATRIBUTO INT UNIQUE,
    DESC_ATRIBUTO VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_TIPO_DOC, ID_ATRIBUTO)
);

CREATE TABLE EXPEDIENTE (
    ID_EXPEDIENTE INT PRIMARY KEY,
    ID_TRAMITE INT NOT NULL,
    DNI_SOLICITANTE VARCHAR(20) NOT NULL,
    FECHA_SOLICITUD DATE NOT NULL,
    ESTADO VARCHAR(50) NOT NULL,
    FECHA_ACTUALIZACION DATE,
    FOREIGN KEY (ID_TRAMITE) REFERENCES TRAMITE(ID_TRAMITE)
);

CREATE TABLE DOC_ADJ (
    ID_DOC INT PRIMARY KEY,
    ID_EXPEDIENTE INT NOT NULL,
    ID_TIPO_DOC INT NOT NULL,
    FOREIGN KEY (ID_EXPEDIENTE) REFERENCES EXPEDIENTE(ID_EXPEDIENTE),
    FOREIGN KEY (ID_TIPO_DOC) REFERENCES DOCUMENTACION(ID_TIPO_DOC)
);

CREATE TABLE INFO (
    ID_DOC INT NOT NULL,
    ID_ATRIBUTO INT NOT NULL UNIQUE,
    VALOR_ATRIBUTO VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_DOC, ID_ATRIBUTO),
    FOREIGN KEY (ID_DOC) REFERENCES DOC_ADJ(ID_DOC),
    FOREIGN KEY (ID_ATRIBUTO) REFERENCES ESTRUCTURA(ID_ATRIBUTO)
);


CREATE TABLE VAL_INFO_DOC (
  ID_TIPO_DOC INT,
  ID_ATRIBUTO INT,
  ID_REGLA INT,
  REGLA_TXT VARCHAR(9000),
  PRIMARY KEY (ID_TIPO_DOC, ID_ATRIBUTO, ID_REGLA)
);

CREATE TABLE COMP_DOCS (
  ID_TRAMITE INT,
  ID_ATRIBUTO_A INT,
  ID_ATRIBUTO_B INT,
  ID_REGLA INT,
  REGLA_TXT VARCHAR(9000),
  FOREIGN KEY (ID_ATRIBUTO_A) REFERENCES INFO (ID_ATRIBUTO),
  FOREIGN KEY (ID_ATRIBUTO_B) REFERENCES INFO (ID_ATRIBUTO),
  FOREIGN KEY (ID_TRAMITE) REFERENCES TRAMITE(ID_TRAMITE),
  PRIMARY KEY (ID_TRAMITE, ID_ATRIBUTO_A, ID_ATRIBUTO_B, ID_REGLA)
)